local function set(name, args)
	vim.api.nvim_set_hl(0, name, args)
end

vim.cmd("highlight clear")
vim.cmd("syntax reset")

local colors = require("colors")
set("Normal", { bg = "none", fg = colors.fg })
set("NonText", { bg = "none", fg = "none" })
set("CursorLine", { bg = colors.bg_tertiary })
set("LineNr", { fg = colors.grey, italic = true })
set("CursorLineNr", { fg = colors.fg, bold = true })
set("ColorColumn", { bg = colors.bg_secondary })
set("Directory", { fg = colors.light_blue })
set("Visual", { bg = colors.bg_tertiary })
set("Search", { bg = colors.accent, fg = colors.fg })
set("MatchParen", { bg = colors.bg_tertiary, fg = colors.fg, underline = true })
set("Pmenu", { bg = "none", fg = colors.fg })
set("PmenuSel", { bg = colors.accent, fg = colors.fg })
set("PmenuSbar", { bg = colors.bg_secondary, fg = colors.grey })
set("VertSplit", { fg = colors.grey })
set("NormalFloat", { bg = "none", fg = colors.fg })
set("WinSeparator", { bg = "none", fg = colors.grey })
set("FloatBorder", { link = "WinSeparator" })
set("Title", { fg = colors.fg, bold = true })

set("SnacksIndent", { fg = colors.bg_secondary })
set("SnacksIndentScope", { fg = colors.dark_grey })
set("SnacksPickerInputBorder", { fg = colors.accent })
set("SnacksPickerIcon", { link = "SnacksPickerInputBorder" })
set("SnacksPickerPrompt", { link = "SnacksPickerInputBorder" })

set("NoiceCmdlinePopupBorder", { link = "SnacksPickerInputBorder" })
set("NoiceCmdlineIcon", { link = "SnacksPickerInputBorder" })

set("Comment", { fg = colors.light_grey, italic = true })
set("Delimiter", { fg = colors.fg })
set("@punctuation.special", { link = "Delimiter" })
set("@constructor.lua", { link = "Delimiter" })
set("Constant", { fg = colors.orange })
set("Keyword", { fg = colors.light_magenta, italic = true })
set("String", { fg = colors.lime })
set("Identifier", { fg = colors.light_blue })
set("Function", { fg = colors.cyan })
set("@variable", { link = "Identifier" })
set("@variable.member", { link = "Identifier" })
