#!/usr/bin/env bash

# Get data
weather=`curl -sf "http://api.openweathermap.org/data/2.5/weather?APPID="$OPENWEATHER_KEY"&id="$OPENWEATHER_CITY_ID"&units="$OPENWEATHER_UNIT""`

if [ ! -z "$weather" ]; then
	temp=`echo "$weather" | jq ".main.temp | tonumber | round"`
	feels_like=`echo "$weather" | jq ".main.feels_like | tonumber | round"`
	high=`echo "$weather" | jq ".main.temp_max | tonumber | round"`
	low=`echo "$weather" | jq ".main.temp_min | tonumber | round"`
	sunrise=`date --date="@$(echo "$weather" | jq ".sys.sunrise")" '+%H:%M'`
	sunset=`date --date="@$(echo "$weather" | jq ".sys.sunset")" '+%H:%M'`
	desc=`echo "$weather" | jq -r ".weather[0].description"`
	city=`echo "$weather" | jq -r ".name"`

	icon_code=`echo "$weather" | jq -r ".weather[0].icon"`

	# https://openweathermap.org/weather-conditions
	if [ "$icon_code" == "50d"  ]; then
		icon=""
		quote="Forecast says it's misty | Make sure you don't get lost on your way..."
		hex="#84afdb"
	elif [ "$icon_code" == "50n"  ]; then
		icon=""
		quote="Forecast says it's a misty night | Don't go anywhere tonight or you might get lost..."
		hex="#84afdb"
	elif [ "$icon_code" == "01d"  ]; then
		icon=""
		quote="It's a sunny day, gonna be fun! | Don't go wandering all by yourself though..."
		hex="#ffd86b"
	elif [ "$icon_code" == "01n"  ]; then
		icon=""
		quote="It's a clear night | You might want to take a evening stroll to relax..."
		hex="#fcdcf6"
	elif [ "$icon_code" == "02d"  ]; then
		icon=""
		quote="It's  cloudy, sort of gloomy | You'd better get a book to read..."
		hex="#adadff"
	elif [ "$icon_code" == "02n"  ]; then
		icon=""
		quote="It's a cloudy night | How about some hot chocolate and a warm bed?"
		hex="#adadff"
	elif [ "$icon_code" == "03d"  ]; then
		icon=""
		quote="It's  cloudy, sort of gloomy | You'd better get a book to read..."
		hex="#adadff"
	elif [ "$icon_code" == "03n"  ]; then
		icon=""
		quote="It's a cloudy night | How about some hot chocolate and a warm bed?"
		hex="#adadff"
	elif [ "$icon_code" == "04d"  ]; then
		icon=" "
		quote="It's cloudy, sort of gloomy | You'd better get a book to read..."
		hex="#adadff"
	elif [ "$icon_code" == "04n"  ]; then
		icon=""
		quote="It's a cloudy night | How about some hot chocolate and a warm bed?"
		hex="#adadff"
	elif [ "$icon_code" == "09d"  ]; then
		icon=""
		quote="It's rainy, it's a great day! | Get some ramen and watch as the rain falls..."
		hex="#6b95ff"
	elif [ "$icon_code" == "09n"  ]; then
		icon=""
		quote=" It's gonna rain tonight it seems | Make sure your clothes aren't still outside..."
		hex="#6b95ff"
	elif [ "$icon_code" == "10d"  ]; then
		icon=""
		quote="It's rainy, it's a great day! | Get some ramen and watch as the rain falls..."
		hex="#6b95ff"
	elif [ "$icon_code" == "10n"  ]; then
		icon=""
		quote=" It's gonna rain tonight it seems | Make sure your clothes aren't still outside..."
		hex="#6b95ff"
	elif [ "$icon_code" == "11d"  ]; then
		icon=""
		quote="There's storm for forecast today | Make sure you don't get blown away..."
		hex="#ffeb57"
	elif [ "$icon_code" == "11n"  ]; then
		icon=""
		quote="There's gonna be storms tonight | Make sure you're warm in bed and the windows are shut..."
		hex="#ffeb57"
	elif [ "$icon_code" == "13d"  ]; then
		icon=""
		quote="It's gonna snow today | You'd better wear thick clothes and make a snowman as well!"
		hex="#e3e6fc"
	elif [ "$icon_code" == "13n"  ]; then
		icon=""
		quote="It's gonna snow tonight | Make sure you get up early tomorrow to see the sights..."
		hex="#e3e6fc"
	elif [ "$icon_code" == "40d"  ]; then
		icon=""
		quote="Forecast says it's misty | Make sure you don't get lost on your way..."
		hex="#84afdb"
	elif [ "$icon_code" == "40n"  ]; then
		icon=""
		quote="Forecast says it's a misty night | Don't go anywhere tonight or you might get lost..."
		hex="#84afdb"
	else 
		icon=""
		quote="Sort of odd, I don't know what to forecast | Make sure you have a good time!"
		hex="#adadff"
	fi
else
	temp="??"
	feels_like="??"
	high="??"
	low="??"
	sunrise="00:00"
	sunset="00:00"
	desc="failed"
	city="???"
	icon=" "
	quote="Fetching the weather failed..? | Maybe go touch grass and find out for yourself."
	hex="#adadff"
	image=""
fi

echo -n "{"
echo -n "\"temp\":\"$temp\","
echo -n "\"feels_like\":\"$feels_like\","
echo -n "\"high\":\"$high\","
echo -n "\"low\":\"$low\","
echo -n "\"sunrise\":\"$sunrise\","
echo -n "\"sunset\":\"$sunset\","
echo -n "\"desc\":\"$desc\","
echo -n "\"city\":\"$city\","
echo -n "\"icon\":\"$icon\","
echo -n "\"icon_code\":\"$icon_code\","
echo -n "\"hex\":\"$hex\","
echo -n "\"quote_1\":\"${quote%|*}\","
echo -n "\"quote_2\":\"${quote#*|}\""
echo "}"
