#!/usr/bin/env bash

socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r event; do 
    if [[ $event =~ ^activewindow\>\>([^,]*),(.*)$ ]]; then #set focused workspace
        class="${BASH_REMATCH[1]}"
        title="${BASH_REMATCH[2]}"
        iconpath=$(geticons "$class" -s 24 -c 1 | head -n 1)
        echo "{\"title\":\"${title//\"/\\\"}\",\"icon\":\"${iconpath//\"/\\\"}\",\"class\":\"${class//\"/\\\"}\"}"
    fi
done
