#!/usr/bin/env bash

# BRIGHT=$(xbacklight -get)
MAX_BRIGHTNESS=$(cat /sys/class/backlight/acpi_video0/max_brightness)
CURRENT_BRIGHTNESS=$(cat /sys/class/backlight/acpi_video0/brightness)
BRIGHT=$(echo "($CURRENT_BRIGHTNESS * 100) / $MAX_BRIGHTNESS" | bc)

get() {
	echo -n "{"
	if [[ ($BRIGHT -lt 30) ]]; then
		echo -n '"level":0'
	elif [[ ($BRIGHT -lt 60) ]]; then
		echo -n '"level":1'
	else
		echo -n '"level":2'
	fi
	echo -n ",\"perc\":$BRIGHT}"
}

set() {
	if [[ "$1" =~ ^[0-9]+$ && "$1" -ge 0 && "$1" -le 100 ]]; then
		local new=$(echo "$MAX_BRIGHTNESS * ($1 / 100)" | bc -l)
		new=$( printf "%.0f" $new )
		echo "424242" | sudo -S sh -c "echo \"$new\" > /sys/class/backlight/acpi_video0/brightness"
	else
		echo "Enter a number 0-100. This is a percentage"
	fi
}

clamp() {
    local value=$1
    local minimum=$2
    local maximum=$3

    if ((value < minimum)); then
        value=$minimum
    elif ((value > maximum)); then
        value=$maximum
    fi

    return $value
}

inc() {
	if [[ "$1" =~ ^-?[0-9]+$ ]]; then
		local new=$(($CURRENT_BRIGHTNESS + $1))
		clamp $new 0 $MAX_BRIGHTNESS
		new=$?
		echo "424242" | sudo -S sh -c "echo \"$new\" > /sys/class/backlight/acpi_video0/brightness"
	else
		echo "Enter a number to change by. Brightness: $CURRENT_BRIGHTNESS / $MAX_BRIGHTNESS ($BRIGHT%)"
	fi
}

if [[ $1 == '--get' ]]; then
	get
elif [[ $1 == '--set' ]]; then
	set $2
elif [[ $1 == '--chg' ]]; then
	inc $2
else
	echo "Unknown command, please use --get, --set, or --chg"
fi
