#!/usr/bin/env python3

import calendar
import sys
from datetime import datetime


calendar.setfirstweekday(calendar.SUNDAY)

if sys.argv[1] == "current":
    # Get the current year
    year = datetime.now().year
    month = datetime.now().month
else:
    year = int(sys.argv[1])
    month = int(sys.argv[2])

cal = calendar.monthcalendar(year, month)
prev_cal = calendar.monthcalendar(
    year - 1 if month == 1 else year, 12 if month == 1 else month - 1
)
next_cal = calendar.monthcalendar(
    year + 1 if month == 12 else year, 1 if month == 12 else month + 1
)
if cal[0][0] == 0:
    cal[0] = [prev_cal[-1][i] or cal[0][i] for i in range(7)]
cal[-1] = [cal[-1][i] or next_cal[0][i] for i in range(7)]

if len(cal) == 4:
    cal.insert(0, prev_cal[-1])
if len(cal) <= 5:
    cal.append(next_cal[0] if next_cal[0][0] == 1 else next_cal[1])

print(cal)
