#!/usr/bin/env bash

active_windows=$(eww active-windows)
[[ $active_windows == *"music-overlay"* ]] && eww close music-overlay
[[ $active_windows == *"audio-overlay"* ]] && eww close audio-overlay
[[ $active_windows == *"wifi-overlay"* ]] && eww close wifi-overlay
[[ $active_windows == *"brightness-overlay"* ]] && eww close brightness-overlay
[[ $active_windows == *"power-overlay"* ]] && eww close power-overlay
[[ $active_windows == *"notifications-overlay"* ]] && eww close notifications-overlay

[[ $active_windows != *"$1"* ]] && eww open $1
