#!/usr/bin/env bash

# Get the current monitor's name.
# Assume it starts with `eDP`
info=$(xrandr)
monitor=$(echo $info | grep -o 'eDP.* connected' | grep -o 'eDP.* ')
if [[ "$info" == *"60.00*"* ]]; then
    new_rate="144.00"
else
    new_rate="60.00"
fi

echo "Setting $monitor to $new_rate Hz"

# Set the new refresh rate.
xrandr --output $monitor --rate $new_rate
