{
  mode,
  lib,
  ...
}: {
  imports =
    [
      ./vscode
      ./alacritty.nix
      ./bat.nix
      ./chromium.nix
      ./dconf.nix
      ./eza.nix
      ./fd.nix
      ./firefox.nix
      ./fish.nix
      ./gh.nix
      ./git.nix
      ./gitui.nix
      ./gtk.nix
      ./kitty.nix
      ./mpv.nix
      ./neovim.nix
      ./obs-studio.nix
      ./ripgrep.nix
      ./starship.nix
      ./thunderbird.nix
      ./wofi.nix
      ./yazi.nix
      ./yt-dlp.nix
      ./zoxide.nix
    ]
    ++ lib.optionals (mode == "hypr") [
      ./hyprland.nix
      ./hyprlock.nix
      ./pywal.nix
      ./waybar.nix
    ];
}
