#!/usr/bin/env bash

download() {
	for url in "$@"; do
		if [[ "$url" == *"/track/"* ]]; then
			yt-dlp \
				-o "$XDG_MUSIC_DIR/%(artist).60s - Singles/%(artist).60s - %(track).60s.%(ext)s" \
				--write-thumbnail \
				--embed-thumbnail \
				--embed-metadata \
				--parse-metadata "%(tags|)l:%(genre)s" \
				--parse-metadata "%(track_number|1)s:%(track_number)s" \
				--parse-metadata "%(album,track)s:%(album)s" \
				-f "ba" \
				"$url"
		elif [[ "$url" == *"/album/"* ]]; then
			yt-dlp \
				-o "$XDG_MUSIC_DIR/%(artist).60s - %(album).60s/%(track_number)02d  %(track).60s.%(ext)s" \
				-o "thumbnail:$XDG_MUSIC_DIR/%(artist).60s - %(album).60s/cover.%(ext)s" \
				--no-overwrite \
				--write-thumbnail \
				--embed-thumbnail \
				--embed-metadata \
				--parse-metadata "%(tags|)l:%(genre)s" \
				-f "ba" \
				"$url"
		elif [[ "$url" == *"watch?v="* ]]; then
			yt-dlp \
				-o "$XDG_MUSIC_DIR/%(uploader).60s - Singles/%(uploader).60s - %(title).60s.%(ext)s" \
				--write-thumbnail \
				--embed-thumbnail \
				--embed-metadata \
				--parse-metadata "%(tags|)l:%(genre)s" \
				--parse-metadata "%(track_number|1)s:%(track_number)s" \
				--parse-metadata "%(album,title)s:%(album)s" \
				-x --audio-format "mp3" --no-keep-video \
				"$url"
		else
			echo "Unknown URL: $url" >&2
		fi
	done
}

if [[ "$#" -gt 0 ]]; then
	download $@
else
	while true; do
		read -rp "URL: " -e urls
		url_arr=($urls)
		download ${url_arr[@]}
	done
fi
