#!/usr/bin/env bash
# A rebuild script that commits on a successful build
set -e

profile=$1
if [ -z "$profile" ]; then
	echo "Please pass a profile to this script"
	exit 1
fi

# cd to your config dir
pushd ~/nixos/

# Edit your config
$EDITOR

echo "NixOS Rebuilding..."

# Fix issues with Nix not finding files
git add .
# Shows your changes
git diff --staged -U0 ./**/*.nix

# Get current generation metadata
generation=$(nixos-rebuild list-generations | grep True | awk '{print $1;}')
# Get a commit name
read -rp "Commit message:  ($generation) " commit_msg

# I don't know why this is needed but it is
# TODO: Fix this
rm -f -- /home/dooshii/.mozilla/firefox/dooshii/search.json.mozlz4.hmbackup /home/dooshii/.config/plover/plover.cfg.hmbackup

# Rebuild, output simplified errors, log tracebacks
sudo nixos-rebuild switch --show-trace --flake .#"$profile"

# Commit all changes witih the generation metadata
# If an argument is provided, append it to the commit message
git commit -m "($generation) $commit_msg"

# Back to where you were
popd

# Notify all OK!
notify-send -e "NixOS Rebuilt OK!" --icon=software-update-available
